# Site settings
title: "XXM's Blog"
description: "a"
keywords: "Likis,XXM,XXM工作室,FSDRI"
author: "Likis"
baseurl: ""
url: "http://xxm-ws.com"
exclude: [README.md, Rakefile, node_modules, Procfile]

duoshuo: Likis
qq: 83885877
email: hhx.xxm@gmail.com

# Map settings
# map_provider: http://api.map.baidu.com/staticimage?width=600&height=300&zoom=13&center=
# last_lat: 31.973991
# last_lng: 118.787754

# Build settings
truncate: 300
paginate: 5
permalink: /:title/
paginate_path: "/page/:num/"
markdown: kramdown
future: true
highlighter: true
